language: python
python:
    - 2.7
    - pypy

cache:
    directories:
        - $HOME/.cache/pip


install:
    - pip install -U pip
    - pip install -r requirements.txt -r test-requirements.txt flake8 flake8-import-order
    - npm install pa11y

script:
    - py.test
    - flake8
    - twistd -o efolder-express --demo
    - "pa11y --level='error' http://127.0.0.1:8080/efolder-express/"
    - "pa11y --level='error' http://127.0.0.1:8080/efolder-express/download/started/"
