language: python
python:
    - 2.7
    - pypy

cache:
    directories:
        - node_modules
        - $HOME/.cache/pip


install:
    - pip install -U pip
    - pip install -r requirements.txt -r test-requirements.txt flake8 flake8-import-order
    - npm install pa11y

script:
    - py.test
    - flake8
