language: python
python:
    - 2.7
    - pypy

cache:
    npm: true
    directories:
        - $HOME/.cache/pip


install:
    - pip install -U pip
    - pip install -r requirements.txt -r test-requirements.txt flake8 flake8-import-order
    - npm install -g pa11y

script:
    - py.test
    - flake8
