# This configuration hits the VBSM "test" environment

vbms:
    endpoint_url: https://filenet.test.vbms.aide.oit.va.gov/vbmsp2-cms/streaming/eDocumentService-v4
    keyfile: /Users/alex_gaynor/projects/va/vbms-credentials/test/client3.jks
    samlfile: /Users/alex_gaynor/projects/va/vbms-credentials/test/samlToken-cui-tst.xml
    keypass: importkey

connect_vbms:
    path: /Users/alex_gaynor/projects/va/connect_vbms/
    bundle_path: /Users/alex_gaynor/.gem/ruby/2.2.0/bin/bundle

tls:
    certificate: /Users/alex_gaynor/projects/va/download-efolder/dev/cert.pem
    dh_parameters: /Users/alex_gaynor/projects/va/download-efolder/dev/dhparams.pem

db:
    uri: sqlite:///dev.db

encryption_keys:
    - "HA6EtTVMI0qTDnSSKtWdZxmJFA8lFb0NrJiZYiNsTYs="

http:
    http_port: 8080
    https_port: 8081
