env: uat

vbms:
    endpoint_url: https://filenet.uat.vbms.aide.oit.va.gov/vbmsp2-cms/streaming/eDocumentService-v4
    keyfile: /Users/alex_gaynor/projects/va/vbms-credentials/uat/uat-w-key3.jks
    samlfile: /Users/alex_gaynor/projects/va/vbms-credentials/uat/SamlTokenCUI-UAT.xml
    key: /Users/alex_gaynor/projects/va/vbms-credentials/uat/CUI-UAT-Client.key
    keypass: Password123.
    ca_cert: /Users/alex_gaynor/projects/va/vbms-credentials/uat/ca2.crt
    client_cert: /Users/alex_gaynor/projects/va/vbms-credentials/uat/CUI-UAT-Client.crt

connect_vbms:
    path: /Users/alex_gaynor/projects/va/connect_vbms/
    bundle_path: /Users/alex_gaynor/.gem/ruby/2.0.0/bin/bundle

db:
    uri: sqlite:///dev-uat.db

storage:
    filesystem: /Users/alex_gaynor/projects/va/efolder-express/media/

encryption_keys:
    - "HA6EtTVMI0qTDnSSKtWdZxmJFA8lFb0NrJiZYiNsTYs="
